### ISSUE TITLE
Invalid SQRT

### ISSUE THREAD

**Issue by ivan866** [thomas-haslwanter/scikit-kinematics#13]
rotmat.py:300: RuntimeWarning: invalid value encountered in sqrt q[3] = 0.5 * np.copysign(np.sqrt(1-R11-R22+R33), R21-R12)

This is the data in question: [skinematics-invalid-sqrt.txt](https://github.com/thomas-haslwanter/scikit-kinematics/files/1569020/skinematics-invalid-sqrt.txt)

**Comment by thomas-haslwanter** [comment]
Can you please tell me how you use the file "skinematics-invalid-sqrt.txt" to get to the RuntimeWarning?


Also, I have gone back to the original sequence in "analytical", and used named variables (according to your suggestion).

I am a bit unsure if unnamed variables are not more "concise". Your opinion would be appreciated!

---
Prof. (FH) PD Dr. Thomas Haslwanter
School of Applied Health and Social Sciences University of Applied Sciences Upper Austria FH OÖ Studienbetriebs GmbH
Garnisonstraße 21
4020 Linz/Austria
Tel.: +43 (0)5 0804 -52170
Fax: +43 (0)5 0804 -52171
E-Mail: Thomas.Haslwanter@fh-linz.at
Web: bim.fh-linz.at
or work.thaslwanter.at

________________________________

**Comment by thomas-haslwanter** [comment]
That was one of the typical problems when using rotation matrices. Went to quaternions (in "imus.analytical"), so the problem should be fixed now.

**Comment by ivan866** [comment]
Is there a way in `numpy` to deal with such situations when expected value of 0.0 is calculated as a very small negative fraction before sending it to `sqrt()`?

**Comment by thomas-haslwanter** [comment]
No :(


---
Prof. (FH) PD Dr. Thomas Haslwanter
School of Applied Health and Social Sciences University of Applied Sciences Upper Austria FH OÖ Studienbetriebs GmbH
Garnisonstraße 21
4020 Linz/Austria
Tel.: +43 (0)5 0804 -52170
Fax: +43 (0)5 0804 -52171
E-Mail: Thomas.Haslwanter@fh-linz.at
Web: bim.fh-linz.at
or work.thaslwanter.at

________________________________
