### ISSUE TITLE
view.orientation slow

### ISSUE THREAD

**Issue by ivan866** [thomas-haslwanter/scikit-kinematics#14]
v.0.6.8 view.orientation seems to cache the whole data when dealing with large datasets, thus yielding a long delay before showing the Tk window

**Comment by thomas-haslwanter** [comment]
hmm, I have noticed that it is slow. But matplotlib seems to be a bit limited with animations, and using the 
`animation.FuncAnimation`
was the only way I thought I could do it.
Do you have any ideas how else to do it?

**Comment by ivan866** [comment]
Probably should use OpenGL surfaces, anyhow this is how 3D plots are done in R.

**Comment by thomas-haslwanter** [comment]
I have played around a bit with PyOpenGL, but still have a few problems. Do you have any experience with OpenGL?

**Comment by ivan866** [comment]
Usually using OpenGL involves these steps:
getting GPU context
determining array of vertices
constructing them into triangles according to chosen winding rule
sending them to render

Pls check my comments in Closed issues #10, #9 section.

**Comment by thomas-haslwanter** [comment]
Hi Ivan,


Maybe you can help me with this:


The attached program does a visualization with OpenGL (not the quaternions yet, but that is a small problem) - but I would really like to view the scene from higher up and right. Any idea what I would have to do?


Thank,

thomas


---
Prof. (FH) PD Dr. Thomas Haslwanter
School of Applied Health and Social Sciences University of Applied Sciences Upper Austria FH OÖ Studienbetriebs GmbH
Garnisonstraße 21
4020 Linz/Austria
Tel.: +43 (0)5 0804 -52170
Fax: +43 (0)5 0804 -52171
E-Mail: Thomas.Haslwanter@fh-linz.at
Web: bim.fh-linz.at
or work.thaslwanter.at

________________________________

**Comment by ivan866** [comment]
The preliminary result is that by using `glRotatef` you rotate the camera, not the model. What you need to do is find a function which takes your model and rotates it like a 3D object in space, and just tilt your camera once beforehand.

**Comment by ivan866** [comment]
Have tested `Orientation_OGL`. Works like charm.
