### ISSUE TITLE
Denavit-Hartenberg convention

### ISSUE THREAD

**Issue by thomas-haslwanter** [thomas-haslwanter/scikit-kinematics#20]
Tommy, I think it would be better to implement it with a "spatial transformation matrix" , as
```
import skinematics as skin
def stm(axis, angle, translation):
    """Spatial Transformation Matrix"""
    stm = np.diag([0,0,0,1.0])
    stm[:-1,:-1] = skin.rotmat.R(axis, angle)
    stm[:3,-1] = translation
    return stm
```

**Comment by tommy3001** [comment]
Ok. I understand the way you suggest to implement it. Important is here the special convention regarding the order and axis for the denavit hartenberg convention. But that can be done as a wrapper of this stm() function.  I will be able to do it. Please give me a few days.

**Comment by thomas-haslwanter** [comment]
stm is now implemented in the module "rotmat.py"
