### ISSUE TITLE
Sample rate vs. Sample period

### ISSUE THREAD

**Issue by Massendefekt** [thomas-haslwanter/scikit-kinematics#26]
There seems to be an inconsistency with the use of the sample rate when comparing the Kalman filter to the Madgwick filter. 

The Kalman filter takes a rate in Hz as input (which is later converted into seconds) while the Madgwick filter takes a sample period in seconds. This makes it inconvenient to use the same `input_data` for both filters.

Is it possible to adjust this issue? I'm also ready to submit a PR if needed.

**Comment by lembit1** [comment]
I strongly support standardizing on using either sample rate or period. In some places the rate is integer type, while really should be able to use float.

**Comment by thomas-haslwanter** [comment]
I agree with the suggestions. They are implemented in the next release.
