### ISSUE TITLE
expose Kalman tunable parameters

### ISSUE THREAD

**Issue by lembit1** [thomas-haslwanter/scikit-kinematics#30]
Yun and Bachman used a legacy sensor combination for their paper, and gave appropriate empirical values for process noise variance D, gyro noise variance r_angvel and quaternion noise variance r_quats. The kalman() implementation hard-codes these parameters, as well as the arm movement time constant tau. Please make these tuning parameters more easily accessible: bring these up into the function call.

**Comment by thomas-haslwanter** [comment]
Good suggestion, implemented in the next release.
