### ISSUE TITLE
Madgwick and Mahony Update() does not support arrays with shape (N,3)

### ISSUE THREAD

**Issue by solarjoe** [thomas-haslwanter/scikit-kinematics#32]
The doc states that input for `Madgwick.Update` and `Mahony.Update` can be numpy arrays of shape (N,3). 

I don't think this works as both functions use the line 

`np.hstack([0, Gyroscope])`

which throws 

`ValueError: all the input arrays must have same number of dimensions`

**Comment by thomas-haslwanter** [comment]
Thanks for the information - You are correct.
I will update the documentation.
