### ISSUE TITLE
Cannot import skinematics -- no module named 'sympy'

### ISSUE THREAD

**Issue by MichaelStetner** [thomas-haslwanter/scikit-kinematics#4]
I just installed this package on a new computer using `pip install scikit-kinematics`. When I try to `import skinematics` I get an error that says `ImportError: No module named 'sympy'`

I resolved this issue by manually installing sympy, but I shouldn't have to do that. pip should automatically install sympy and all the other dependencies if necessary.

**Comment by MichaelStetner** [comment]
Fixed in this pull request: #5

**Comment by thomas-haslwanter** [comment]
Fixed - Thanks a lot!
