### ISSUE TITLE
How to compute distance from positions?

### ISSUE THREAD

**Issue by ogreyesp** [thomas-haslwanter/scikit-kinematics#40]
Hello

I'm very interesting to use this library in my daily work, but I´m having some problems to adapt it. 

I have seen that the function calc_position computes velocity and position.

1- How I can calculate the distance travelled by a user from the list of positions calculated?
2- How I can obtain the specific velocity value in each time step instead of the accumulative value?

Also, I have noted that when "Kalman" option is provided, the operation np.deg2rad is automatically done, How come? What if my data is initially in rad/seg?

Best regards

**Comment by thomas-haslwanter** [comment]
ad 1) The distance traveled is the last position minus the first position. (Do I miss something here?)
ad 2) "cumtrapz" provides the velocity value at eat time step.
ad "Kalman") If your data are in rad/sec, you have to apply np.rad2deg before you apply the Kalman filter.
