### ISSUE TITLE
Measurement unit of gyroscope

### ISSUE THREAD

**Issue by mohataher** [thomas-haslwanter/scikit-kinematics#6]
Hello Thomas:

Nice library. The docs of Madgwick and Mahony classes are probably missing the measurement units to be passed. I'll be happy to contribute to the library docs if you let me know here. 

Thanks,
MTA.

**Comment by thomas-haslwanter** [comment]
Thanks for pointing that out - and sorry that I missed your comment for so long!
It should be fixed now.
Thanks also for your offer to contribute! If you can spare some time, I would be most grateful if I could expand test testing. All the relevant files can be found in the folder "tests". Have a look at them - and if you have any questions, just get back to me.
Best regards, thomas
